import Head from 'next/head';
import Link from 'next/link';
import styles from '../../styles/Home.module.css';
import { prisma } from '../../lib/prisma';

export async function getStaticPaths(){return {paths:[],fallback:'blocking'};}
export async function getStaticProps({params}){const person=await prisma.person.findUnique({where:{slug:params.slug},include:{castCredits:{include:{movie:true},orderBy:{billingOrder:'asc'}},crewCredits:{include:{movie:true}}}});if(!person)return {notFound:true};return {props:{person:JSON.parse(JSON.stringify(person))},revalidate:300};}
function year(date){return date?new Date(date).getFullYear():'';}
export default function PersonPage({person}){return <div className={styles.site}><Head><title>{person.name} — HypeScore</title><meta name="description" content={'Movies featuring '+person.name}/></Head><header className={styles.nav}><div className={styles.navInner}><Link href="/" className={styles.brand}><span className={styles.brandMark}>H</span><span>Hype<span>Score</span></span></Link><nav className={styles.navLinks}><Link href="/#most-hyped">Most Hyped</Link><Link href="/#opening">Opening This Week</Link><Link href="/#coming-soon">Coming Soon</Link></nav><div className={styles.cleanNavRight}><Link href="/leaderboard">Top Hyped</Link><button className={styles.profileButton}>My Hype</button></div></div></header><main className={styles.movieClean}><section className={styles.personHero}><p className={styles.eyebrow}>PERSON</p><h1>{person.name}</h1>{person.biography&&<p className={styles.cleanSubhead}>{person.biography}</p>}</section><section className={styles.cleanSection}><div className={styles.cleanSectionHead}><div><p className={styles.eyebrow}>FILMOGRAPHY</p><h2>Movies</h2></div></div><div className={styles.cleanRail}>{person.castCredits.map(c=><Link key={c.id} href={'/movie/'+c.movie.slug} className={styles.cleanMovie}><div className={styles.cleanPoster}>{c.movie.posterUrl?<img src={c.movie.posterUrl} alt=""/>:<div/>}</div><div className={styles.cleanMovieTitle}>{c.movie.title}</div><div className={styles.cleanMovieMeta}>{year(c.movie.releaseDate)}{c.characterName?' · '+c.characterName:''}</div></Link>)}</div></section></main><footer className={styles.footer}><div><Link href="/" className={styles.brand}><span className={styles.brandMark}>H</span><span className={styles.brandMark}>H</span><span>Hype<span>Score</span></span></Link><p>Track the hype. See what delivered.</p></div><p>© 2026 HypeScore</p></footer></div>}
