export const fallbackMovies = [
  {
    slug: 'spider-man-brand-new-day',
    title: 'Spider-Man: Brand New Day',
    releaseDate: '2026-07-31T00:00:00.000Z',
    runtimeMinutes: null,
    certification: 'PG-13',
    genres: ['Action', 'Adventure', 'Science Fiction'],
    posterUrl: 'https://media.themoviedb.org/t/p/w500/9JCQtDCSpPR2ld55yNlEg1VwcQo.jpg',
    backdropUrl: null,
    tagline: '',
    overview: 'Spider-Man returns for a new chapter.',
    originalLanguage: 'English',
    productionCompanies: [],
    budgetUsd: null,
    boxOfficeWorldwideUsd: null,
    criticAverage: 0,
    criticReviewCount: 0,
    audienceAverage: 0,
    audienceRatingCount: 0,
    trailerUrl: '',
    sourceProvider: 'tmdb',
    tmdbId: 969681,
    hype: 94,
    cast: []
  },
  {
    slug: 'the-odyssey',
    title: 'The Odyssey',
    releaseDate: '2026-07-17T00:00:00.000Z',
    runtimeMinutes: 172,
    certification: 'PG-13',
    genres: ['Action', 'Adventure', 'Fantasy'],
    posterUrl: 'https://image.tmdb.org/t/p/w500/x5JKwcrl7NzaSWfTFh6bIPCsqJd.jpg',
    backdropUrl: null,
    tagline: 'Defy the gods.',
    overview: 'Christopher Nolan’s mythic action epic inspired by Homer’s Odyssey.',
    originalLanguage: 'English',
    productionCompanies: [],
    budgetUsd: null,
    boxOfficeWorldwideUsd: null,
    criticAverage: 0,
    criticReviewCount: 0,
    audienceAverage: 0,
    audienceRatingCount: 0,
    trailerUrl: '',
    sourceProvider: 'tmdb',
    tmdbId: null,
    hype: 91,
    cast: []
  },
  {
    slug: 'practical-magic-2',
    title: 'Practical Magic 2',
    releaseDate: '2026-09-11T00:00:00.000Z',
    runtimeMinutes: 130,
    certification: 'PG-13',
    genres: ['Comedy', 'Drama', 'Fantasy'],
    posterUrl: 'https://www.practicalmagicmovie.com/assets/images/mobilebanner.jpg',
    backdropUrl: null,
    tagline: '',
    overview: 'The Owens family faces a new magical threat.',
    originalLanguage: 'English',
    productionCompanies: [],
    budgetUsd: null,
    boxOfficeWorldwideUsd: null,
    criticAverage: 0,
    criticReviewCount: 0,
    audienceAverage: 0,
    audienceRatingCount: 0,
    trailerUrl: '',
    sourceProvider: 'official',
    tmdbId: null,
    hype: 87,
    cast: []
  },
  {
    slug: 'dune-part-three',
    title: 'Dune: Part Three',
    releaseDate: '2026-12-18T00:00:00.000Z',
    runtimeMinutes: null,
    certification: null,
    genres: ['Science Fiction', 'Adventure', 'Drama'],
    posterUrl: 'https://dx35vtwkllhj9.cloudfront.net/warnerbros/dune-part-three/images/regions/us/onesheet.jpg',
    backdropUrl: null,
    tagline: '',
    overview: 'The next chapter in the Dune saga.',
    originalLanguage: 'English',
    productionCompanies: [],
    budgetUsd: null,
    boxOfficeWorldwideUsd: null,
    criticAverage: 0,
    criticReviewCount: 0,
    audienceAverage: 0,
    audienceRatingCount: 0,
    trailerUrl: '',
    sourceProvider: 'official',
    tmdbId: null,
    hype: 93,
    cast: []
  }
];

export function getFallbackMovie(slug) {
  return fallbackMovies.find(movie => movie.slug === slug) || null;
}
